version: '3.7'
services:
  quizlet:
    container_name: quizlet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/circleci'
      - '/home/circleci/node_modules'
    ports:
      - '9966:3000'
    environment:
      - NODE_ENV=development
