version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10-jessie-browsers
    steps:
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-repo-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies with yarn
          command: yarn install # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: |
            yarn test
      - run:
          name: End to end test with cypress
          command: |
            yarn cp
      - store_artifacts:
          path: test-results

      - store_test_results:
          path: test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
